In [17]:
import torch
import torch.nn as nn
import torch.nn.functional as F

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Using device: {device}')

print(torch.version.cuda)

Using device: cpu
None


In [18]:
%%time
if torch.cuda.is_available():
    mat = mat.cuda()
    torch.mm(mat.t(), mat)
else:
    print('GPU is not available!')

GPU is not available!
Wall time: 1.26 ms


In [19]:
torch.cuda.is_available()

False

In [20]:
pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [21]:
pip install tensorflow_hub

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [22]:
import tensorflow_hub as hub
import pandas as pd

embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder/4")
embeddings = embed([
    "The quick brown fox jumps over the lazy dog.",
    "I am a sentence for which I would like to get its embedding"])

pd.DataFrame(embeddings)

0         1         2         3         4         5         6    \
0 -0.031330 -0.063386 -0.016075 -0.010349 -0.046501  0.037232  0.005916   
1  0.050809 -0.016524  0.015738 -0.042864 -0.043725 -0.025362 -0.073212   

        7         8         9    ...       502       503       504       505  \
0  0.071744  0.016664  0.060908  ... -0.019596  0.057343  0.055932  0.017127   
1  0.040799  0.017489  0.012179  ... -0.035752  0.103115  0.107388 -0.071464   

        506       507       508       509       510       511  
0  0.073472 -0.078552  0.064889 -0.032428 -0.045757  0.053705  
1 -0.027945 -0.020117 -0.016280  0.009767  0.031701  0.017881  

[2 rows x 512 columns]

In [24]:
from keras.preprocessing.text import Tokenizer
import pandas as pd
import numpy as np

docs = [
  'the cat sat',
  'the cat sat in the hat',
  'the cat with the hat',
]

## Step 1: Determine the Vocabulary
tokenizer = Tokenizer()
tokenizer.fit_on_texts(docs)
print(f'Vocabulary: {list(tokenizer.word_index.keys())}')

## Step 2: Count
vectors = tokenizer.texts_to_matrix(docs, mode='count')
print(vectors)

from sklearn.feature_selection import RFECV
from sklearn.tree import ExtraTreeClassifier

X = vectors
y = [0,0,1]

estimator = ExtraTreeClassifier()
selector = RFECV(estimator, step=1, cv=2)
selector = selector.fit(X, y)

print(selector.support_)

X = X[:,selector.support_]
X

Vocabulary: ['the', 'cat', 'sat', 'hat', 'in', 'with']
[[0. 1. 1. 1. 0. 0. 0.]
 [0. 2. 1. 1. 1. 1. 0.]
 [0. 2. 1. 0. 1. 0. 1.]]
[False False False  True False False False]


c:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(


array([[1.],
       [1.],
       [0.]])